### PR TITLE
v4: build-time Mantine theme integration

### LINKED ISSUE #17: Import tree contains CSS modules
In one of my files imported by the theme.ts module I import a CSS module. This causes the following error:

Error generating theme: Unknown file extension ".css" for /Users/softonixdeveloper/work/expense-tracker/fe/src/core/styles/mantine/button/button.module.cs

I tried requiring CSS loaders like node-css-require package, but it did not work.

### LINKED ISSUE #20: Generated custom theme doesn't work on pages without MantineProvider.
Hello. Thanks for this great plugin. I'm looking for a suggestion or work around to a problem I'm having with the custom theme generator. 

My application mostly SPA in React but I have some pages like my login form and some emails templates that do not load the application. Because the app is not loaded, Mantine never injects the `<style>` tags with theme colors and the `--mantine-color-XXX` variables do not exist. 

```
/** This file is autogenerated by the script. Do not edit it manually. */
@theme {
  /* colors - all */
  
  --color-senex-50: var(--mantine-color-senex-0); 
  --color-senex-100: var(--mantine-color-senex-1);
...etc
```

Prior to Tailwind v4 i was using Tailwind's `resolveConfig` to inject colors into Mantine and my chart components but they took that away from us. 

As a work around I created a mini app with just `<MantineProvider theme={myTheme]/>` to my login forms. It would be kind of nice if the generated styles could use the theme values instead of referring to the Mantine variables, but I could see how that may affect things like light/dark mode.

### LINKED ISSUE #40: Container query variants (e.g. @xs/navbar:block) silently generate no CSS
**_Note: I used Claude to help me create this description but I still stand behind what he came up with ;)_**

Container query *variants* like `@xs/navbar:block` generate no CSS when using this preset with Tailwind v4. The `@container/navbar` class itself works fine — only the responsive threshold variants are broken.

**Why `w-7xl` works but `@xs/navbar:block` doesn't**

`w-7xl` compiles to:

```
.w-7xl { width: var(--container-7xl); }
```

The var() reference is passed through verbatim and the browser resolves it at runtime. This works fine.

@xs/navbar:block needs to compile to:

```
@container navbar (width >= 20rem) {
  .\@xs\/navbar\:block { display: block; }
}
```

The 20rem threshold must be a literal value baked in at compile time — @container conditions do not support var() (https://drafts.csswg.org/css-contain-3/#typedef-container-query) in CSS. Tailwind must resolve --container-xs during PostCSS compilation, but it cannot follow a var(--size-xs) chain at compile time.

**Root cause**

Introduced in the fix for #24, --container-* is defined via @theme {} (non-inline) with var(--size-*) references:

```
--size-xs: 20rem;
--container-xs: var(--size-xs);
```

The fix is @theme inline {}, which tells Tailwind to resolve var() references eagerly at compile time:

```
@theme inline {
  --size-xs: 20rem;
  --container-xs: var(--size-xs); /* now resolved to 20rem at compile time */
}
```

**Workaround**

Override after the import with direct values:
@import "tailwind-preset-mantine";

```
@theme {
  --container-3xs: 16rem;
  --container-2xs: 18rem;
  --container-xs: 20rem;
  --container-sm: 24rem;
  --container-md: 28rem;
  --container-lg: 32rem;
  --container-xl: 36rem;
  --container-2xl: 42rem;
  --container-3xl: 48rem;
  --container-4xl: 56rem;
  --container-5xl: 64rem;
  --container-6xl: 72rem;
  --container-7xl: 80rem;
}
```

**Versions**
- tailwind-preset-mantine: 3.1.0
- tailwindcss: 4.2.2

### PR DESCRIPTION
**Pull request by songkeys**
## Summary
This PR establishes the v4 direction for the preset:
- Tailwind theme namespaces are generated from the merged Mantine theme
- custom Mantine themes can be loaded at build time through CSS, without a required manual CLI generation step
- pages without `MantineProvider` now have an explicit standalone path
- the default packaged preset path stays zero-config
- restore container query variants like `@xs/navbar:block` by keeping `--container-*` as literal threshold values instead of `var(--size-*)`
- allow Mantine theme graphs to include CSS modules and common asset imports without crashing the theme loader

Fixes #17.
Fixes #20.
Fixes #40.

## What changed
- generate spacing, radius, font size, line height, font weight, shadow, and heading namespaces from the merged Mantine theme
- keep the generator in the original template-string style instead of introducing heavier helper abstraction
- switch the generated output to `@theme inline` so Tailwind resolves Mantine-backed CSS variable references correctly
- map primary outline/text variables to the actual Mantine variables that exist
- keep the existing Tailwind container sizing workaround, add `--flex-basis-*`, and remove the nonstandard container-backed height aliases
- restore literal `--container-*` defaults so Tailwind can emit container query threshold variants again
- keep the packaged CSS for the zero-config default theme path
- add CSS-driven custom Mantine theme loading through `@mantine-theme "./mantine-theme.ts"`
- add an explicit standalone path through `@mantine-standalone "./mantine-theme.ts"` for pages that do not render `MantineProvider`
- add `tailwind-preset-mantine/postcss` and `tailwind-preset-mantine/vite` integrations that expand both directives at build time
- add CLI output modes with `--format theme|standalone`
- add transitive dependency watching in the Vite integration so imported local theme modules also trigger rebuilds
- ignore imported stylesheet and common asset files when loading Mantine theme graphs, so colocated CSS modules, fonts, images, and helper `.tsx` files do not break theme loading
- reorganize the internal source layout into `core`, `integrations`, and `cli`
- move fixtures out of `test/` so the Node test runner no longer scans fixture modules as tests
- add plugin-level integration tests and real PostCSS/Vite e2e coverage, including the standalone path

## Why
The original issue here was that custom merged theme keys like `spacing.xxs` were not getting corresponding Tailwind theme variables, because several namespaces were only emitted in the default-theme path.

At the same time, for v4 I wanted a better DX than “generate a CSS file manually, then import it”. The current direction keeps the simple packaged preset for the default theme, adds a build-time path for custom Mantine themes using explicit CSS directives, and adds a standalone output mode for pages that need Mantine CSS variables without rendering `MantineProvider`.

That gives us:
- zero-config defaults for the common case
- merged-theme-driven Tailwind variables for custom themes
- no required manual generation step in PostCSS/Vite environments
- an explicit standalone path for pages without `MantineProvider`
- support for real theme graphs that include colocated styles and asset imports
- restored support for container query variants like `@xs/...`
- a CLI fallback for other environments

## Validation
- `npm run generate`
- `pnpm lint`
- `pnpm test`
- generator assertions for merged custom keys, breakpoint output, removed height aliases, literal `--container-*` thresholds, and standalone Mantine variable emission
- plugin tests for directive expansion, non-code import handling, Vite transitive dependency watching, and standalone directive expansion
- real PostCSS e2e coverage
- real Vite build e2e coverage
- CLI coverage for theme files that import stylesheets and asset-backed TSX helpers, plus standalone output mode

## Notes
Removing the container-backed height aliases is intentional. It aligns the preset more closely with Tailwind's sizing model while keeping the width/container workaround that previously addressed the `w-*` collision.

### CODE REVIEW

**Comment by songkeys** [comment]
Tried to use codex to generate this 😊

@corydeppen Could you please check and provide some feedback?

`tailwind-preset-mantine@4.0.0-alpha.0`

**Comment by corydeppen** [comment]
@songkeys - The generated theme file appears to be essentially the same as the `index` and `theme` CSS files included in the package. By merging the default theme with overrides, I don't think either of the CSS files needs to be included in the package and devs can instead only import the generated file in their app CSS file.

Just to expand on a few ideas that were in my [PoC branch](https://github.com/corydeppen/tailwind-preset-mantine/tree/gen-merged-theme):

- The `no-tw-defaults` CLI option was added to control whether the Tailwind default variables are included or not, which I thought could help when devs don't want to expose TW variables (i.e. not present in the TW extension autocomplete and not generated if used in source) that aren't part of the Mantine design system.
- The `no-imports` CLI option allows for controlling whether the imports are included in the output, like the existing `theme.css` file. Similar to the other option, this was just to help control the output assuming the CSS files aren't included in the package.

I appreciate your feedback and other ideas.

File: src/core/generate.js [hunk 1]
```diff
@@ -20,46 +37,54 @@ export function generateDefaultImports() {
...
+	--color-primary-text: var(--mantine-color-${primaryColor}-text);
 	--color-primary-filled: var(--mantine-primary-color-filled);
 	--color-primary-filled-hover: var(--mantine-primary-color-filled-hover);
 	--color-primary-light: var(--mantine-primary-color-light);
 	--color-primary-light-hover: var(--mantine-primary-color-light-hover);
 	--color-primary-light-color: var(--mantine-primary-color-light-color);
-	--color-primary-outline: var(--mantine-primary-color-outline);
-	--color-primary-outline-hover: var(--mantine-primary-color-outline-hover);
+	--color-primary-outline: var(--mantine-color-${primaryColor}-outline);
+	--color-primary-outline-hover: var(--mantine-color-${primaryColor}-outline-hover);
```
Comment (corydeppen) [inline src/core/generate.js:121]: I believe these [Mantine primary color variables](https://mantine.dev/styles/css-variables/#primary-color-variables) should be e.g. `--mantine-primary-color-outline` instead of including the primary color string in the variable like `--mantine-color-blue-outline` (same with `--color-primary-text` above). Can you confirm?

File: src/generate.js [hunk 2]
```diff
@@ -20,46 +37,54 @@ export function generateDefaultImports() {
...
+		? "xs"
+		: (shadowKeys[0] ?? "xs");
+	const darkVariant = isDefault
+		? `@custom-variant dark (&:where(
+		[data-mantine-color-scheme="dark"],
+		[data-mantine-color-scheme="dark"] *
+	));`
+		: "";
 
 	return `/** This file is autogenerated by the script. Do not edit it manually. */
```
Comment (corydeppen) [inline src/generate.js]: Consider extracting this comment and conditionally displaying it so it's not duplicated when the comment is included when the default imports are included on line 26 above.

File: src/generate.js [hunk 3]
```diff
@@ -182,131 +129,90 @@ ${
 	--color-${key}-light-color: var(--mantine-color-${key}-light-color);
 	--color-${key}-outline: var(--mantine-color-${key}-outline);
 	--color-${key}-outline-hover: var(--mantine-color-${key}-outline-hover);
-	`.trimEnd(),
+	--color-${key}-contrast: var(--mantine-color-${key}-contrast);`.trim(),
```
Comment (corydeppen) [inline src/generate.js]: I don't think the contrast variable is needed for each color based on the [variables list](https://mantine.dev/styles/css-variables-list/) (only the primary for light and dark it seems). Can you confirm?

File: src/generate.js (hunk 2 above)
Comment (songkeys) [reply src/generate.js]: Fixed in `1787ed9`. `index.css` now imports `./theme.css` instead of embedding the generated theme output, so there is only one autogenerated header and one packaged source of truth for the default theme CSS.

File: src/core/generate.js (hunk 1 above)
Comment (songkeys) [reply src/core/generate.js:121]: Checked Mantine again before changing this. Mantine exposes primary aliases for filled/light/light-hover/light-color/contrast, but it does not expose `--mantine-primary-color-text`, `--mantine-primary-color-outline`, or `--mantine-primary-color-outline-hover`. Those `text` and `outline` variables only exist in the per-color namespace, so `--color-primary-text` and `--color-primary-outline` need to resolve through `--mantine-color-${primaryColor}-*`. I left this mapping as-is for that reason.

**Comment by songkeys** [comment]
> @songkeys - The generated theme file appears to be essentially the same as the `index` and `theme` CSS files included in the package. By merging the default theme with overrides, I don't think either of the CSS files needs to be included in the package and devs can instead only import the generated file in their app CSS file.
> 
> Just to expand on a few ideas that were in my [PoC branch](https://github.com/corydeppen/tailwind-preset-mantine/tree/gen-merged-theme):
> 
> * The `no-tw-defaults` CLI option was added to control whether the Tailwind default variables are included or not, which I thought could help when devs don't want to expose TW variables (i.e. not present in the TW extension autocomplete and not generated if used in source) that aren't part of the Mantine design system.
> * The `no-imports` CLI option allows for controlling whether the imports are included in the output, like the existing `theme.css` file. Similar to the other option, this was just to help control the output assuming the CSS files aren't included in the package.
> 
> I appreciate your feedback and other ideas.

Thanks, this is helpful.

I agree with the direction of reducing duplication in the output. With the latest changes, `index.css` now imports `theme.css`, so there is only one packaged source of truth for the default theme CSS.

I’m less convinced about removing the packaged CSS files entirely and making the generated file the only path. That feels like a larger product decision, since the package currently has a nice zero-config default import, and I’d prefer not to lose that without a separate discussion.

On the CLI flags:
- `no-imports` doesn’t feel necessary in the current setup, since the generated custom theme file is already theme-only.
- `no-tw-defaults` is interesting, but I’d see that as an advanced option rather than something to bundle into this PR.

So, I think the merged-theme generation makes sense and reducing duplication makes sense, but moving to a generator-only model should probably be discussed separately.

**Comment by songkeys** [comment]
Thanks again for pushing on this.

I took the PR a bit further based on that discussion, and I think it ended up in a better place DX-wise than where it started.

Instead of moving all the way to a generator-only model, the current direction is:

- keep the packaged CSS for the zero-config default theme path
- support custom Mantine themes through a CSS directive: `@mantine-theme "./mantine-theme.ts"`
- expand that directive at build time through PostCSS or Vite, so custom theme tokens become available to Tailwind without requiring a manual CLI step
- keep the CLI as a fallback for environments that don’t use either integration

So the default import path stays simple, but the custom theme path no longer depends on hand-generating a CSS file unless someone really wants that workflow.

I also added transitive dependency watching for the Vite integration, so if the Mantine theme imports local files like `theme/colors.ts` or `theme/spacing.ts`, changes to those files trigger rebuilds too.

At this point, I think this gets most of the practical DX benefit you were aiming for, without removing the packaged preset path entirely. I’m still treating `no-imports` / `no-tw-defaults` as out of scope for this PR, but I think the new integration path addresses the bigger usability concern.

File: README.md [hunk 4]
```diff
@@ -106,22 +108,82 @@ const theme = createTheme({
...
+export default {
+  plugins: [mantineTheme(), tailwindcss()],
+};
+```
+
+Vite:
+
+```ts
+import { defineConfig } from "vite";
+import mantineTheme from "tailwind-preset-mantine/vite";
```
Comment (corydeppen) [inline README.md:132]: Using this in `vite.config.ts` results in a TS error:

```sh
Could not find a declaration file for module 'tailwind-preset-mantine/vite'. 'repo/node_modules/.pnpm/tailwind-preset-mantine@https+++codeload.github.com+songkeys+tailwind-preset-mantine+ta_dd3453d41b544d1da9ab5ac0e9bdd252/node_modules/tailwind-preset-mantine/src/integrations/vite.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tailwind-preset-mantine` if it exists or add a new declaration (.d.ts) file containing `declare module 'tailwind-preset-mantine/vite';`
```

File: test/generate.test.js [hunk 5]
```diff
@@ -0,0 +1,145 @@
...
+						lineHeight: "1.1",
+						fontWeight: "800",
+					},
+				},
+			},
+		}),
+	);
+
+	assert.match(css, /@theme inline {/);
+	assert.match(css, /--spacing-xxs: var\(--mantine-spacing-xxs\);/);
```
Comment (corydeppen) [inline test/generate.test.js:48]: It looks like the `--mantine-spacing-xxs` variable is being added to the `:root` selector on each page that uses a class with that value. Is that expected, or should it be added to that selector in the theme layer? For reference, the element also has a Tailwind color class that's generating the CSS variable in the `:root` in the theme layer.

Edit: The variable value being set in a page `style` seems unchanged from before the PR, but the class that's generated uses the Mantine variable (e.g. `.px-xxs { padding-inline: var(--mantine-spacing-xxs); }`) instead of referencing a Tailwind variable (`--spacing-xxs`) that's set to the value of the Mantine variable (i.e. I don't see `--spacing-xxs: var(--mantine-spacing-xxs)` in the generated CSS). Is that intentional when using a custom theme like below?

```css
@import "tailwind-preset-mantine";
@mantine-theme "./theme.ts";
```

Comment (songkeys) [reply test/generate.test.js:48]: Yes, that behavior is intentional.

What `@mantine-theme "./theme.ts"` does in the current design is generate Tailwind theme aliases from the Mantine theme, but the final utilities are still expected to resolve against Mantine’s CSS variables.

Since the generated output uses `@theme inline` now (it was just `@theme` before), Tailwind inlines variable-to-variable mappings when it builds utilities. So if the theme contains:

```css
--spacing-xxs: var(--mantine-spacing-xxs);
```

the resulting utility can end up as:

```css
.px-xxs { padding-inline: var(--mantine-spacing-xxs); }
```

instead of going through `var(--spacing-xxs)` at runtime.

The `:root` and `:host` variables you’re seeing are still being emitted in the theme layer. Tailwind v4 outputs the theme variables it needs for that CSS entry, so seeing those variables in a page stylesheet is expected.

The tradeoff here is that `@mantine-theme` treats Mantine variables as the source of truth. Therefore, this mode assumes those `--mantine-*` variables exist on the page. That is why this PR also adds an explicit standalone path for pages without `MantineProvider`:

```css
@import "tailwind-preset-mantine";
@mantine-standalone "./theme.ts";
```

File: README.md (hunk 4 above)
Comment (songkeys) [reply README.md:132]: Fixed in 4.0.0-alpha.4.

**Comment by corydeppen** [comment]
I just noticed the [Tailwind CSS IntelliSense extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) in VS Code doesn't appear to pick up the generated classes for a custom theme when using the Vite plugin (presumably because the styles can't be statically analyzed by the extension). While this would negatively impact the autocomplete DX, it could also affect those sorting class names since the unknown classes will be brought to the front of the class list.

**Comment by songkeys** [comment]
> I just noticed the [Tailwind CSS IntelliSense extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) in VS Code doesn't appear to pick up the generated classes for a custom theme when using the Vite plugin (presumably because the styles can't be statically analyzed by the extension). While this would negatively impact the autocomplete DX, it could also affect those sorting class names since the unknown classes will be brought to the front of the class list.

I checked. For IDE tooling support, we have to generate a static file instead of relying on runtime. I agree that we should support this UX regardless of the a little bit verbose setup. I have updated the usage and published it in 4.0.0-alpha.5. Could you read the latest README to see the usage and try again to provide more feedback? Thanks!

**Comment by corydeppen** [comment]
Thanks, this works well!

You've mentioned being reluctant to move to a generator-only model at this point, but given this latest update I was interested in your thoughts on the following:

- If the preset or default imports currently have to be imported regardless of whether a custom theme is used, could the default imports be included in the generated output so the theme CSS includes everything and doesn't require separately importing anything from the package?
- Having a single import to include regardless of whether a custom theme is used seems to align with the original spirit of the library and could help make the install steps more consistent and not require changes if/when a custom theme is used.
- A theme TS file is always present, so it seems reasonable to always generate a theme CSS file, including possibly setting the default filename based on the theme TS so it doesn't have to be explicitly specified.

Just thinking out loud - I appreciate your thoughts.

**Comment by songkeys** [comment]
> Thanks, this works well!
> 
> You've mentioned being reluctant to move to a generator-only model at this point, but given this latest update I was interested in your thoughts on the following:
> 
> * If the preset or default imports currently have to be imported regardless of whether a custom theme is used, could the default imports be included in the generated output so the theme CSS includes everything and doesn't require separately importing anything from the package?
> * Having a single import to include regardless of whether a custom theme is used seems to align with the original spirit of the library and could help make the install steps more consistent and not require changes if/when a custom theme is used.
> * A theme TS file is always present, so it seems reasonable to always generate a theme CSS file, including possibly setting the default filename based on the theme TS so it doesn't have to be explicitly specified.
> 
> Just thinking out loud - I appreciate your thoughts.

Thanks. I agree with your points! I adjusted the PR and published a new version. Please try again and see if it's okay.

I still did not want to force generation for the default-theme case, but for custom themes I agree that a single generated import is the cleaner model.

**Comment by corydeppen** [comment]
Looks good - thanks!

File: README.md [hunk 6]
```diff
@@ -106,22 +107,98 @@ const theme = createTheme({
...
+- `-o, --output`: Output file name/location (defaults to the input filename with a `.css` extension)
+- `--format theme|standalone`: Output either Tailwind aliases only (`theme`, default) or Mantine variables plus Tailwind aliases (`standalone`)
 
-3. Import the generated CSS file in your application:
+Then import the generated file:
 
 ```css
-@import "tailwind-preset-mantine";
-@import "./theme.css"; /* <-- add the generated theme */
+@import "./theme.css";
```
Comment (corydeppen) [inline README.md]:
```suggestion
@import "./mantine-theme.css";
```
